language:
  - cpp

compiler:
  - gcc

sudo: false

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-dev
      - python-numpy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev

install:
  - curl -sL https://github.com/Itseez/opencv/archive/3.0.0.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.0.0

  - mkdir build install
  - cd build

  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=$(pwd)/../install -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
  - make -j4
  - make install

  - cd ../../

script:
  - make
